extends:
    - eslint:recommended
    - plugin:react/recommended
plugins:
    - react
parserOptions:
    ecmaVersion: 6
    sourceType: module
env:
    jest: true
    browser: true
rules:
    # Fix Recommended
    comma-dangle:
        - 2
        - only-multiline

    # ECMAScript 6
    no-var: 2
    prefer-const: 2
